parse(file = "app.R")
source("R/audit.R")

app_text <- paste(readLines("app.R", warn = FALSE), collapse = "\n")
stopifnot(grepl("Your improved search string", app_text, fixed = TRUE))
stopifnot(grepl("Start with a naive search", app_text, fixed = TRUE))
stopifnot(grepl("Upload benchmark records", app_text, fixed = TRUE))
stopifnot(!grepl("Stage 4 ·", app_text, fixed = TRUE))
stopifnot(!grepl("Stage 1 ·", app_text, fixed = TRUE))

deploy_text <- paste(readLines("DEPLOYMENT.md", warn = FALSE), collapse = "\n")
stopifnot(grepl("LENS_API_TOKEN", deploy_text, fixed = TRUE))
stopifnot(grepl("manifest.json", deploy_text, fixed = TRUE))

cat("Stage 8 UI and deployment-preparation tests passed.\n")


app_text <- paste(readLines("app.R", warn = FALSE), collapse = "\n")
stopifnot(grepl('class = "search-block border rounded p-3 mb-3"', app_text, fixed = TRUE))
stopifnot(!grepl('card_header(sprintf("Substring %d", i))', app_text, fixed = TRUE))
stopifnot(grepl('Reidentify candidate terms', app_text, fixed = TRUE))
stopifnot(grepl('Citation-chasing comparison becomes available', app_text, fixed = TRUE))
stopifnot(grepl('not a recall target', app_text, fixed = TRUE))
stopifnot(grepl('screened included records', app_text, fixed = TRUE))
stopifnot(grepl('Excluded screened records influence ranking but do not generate candidate terms', app_text, fixed = TRUE))
stopifnot(grepl('Find variants and synonyms', app_text, fixed = TRUE))
stopifnot(grepl('morphological variants', app_text, fixed = TRUE))
stopifnot(grepl('general lexical synonyms', app_text, fixed = TRUE))
stopifnot(grepl('source("R/term_sources.R")', app_text, fixed = TRUE))
stopifnot(!grepl('remain missed', app_text, fixed = TRUE))
stopifnot(grepl('citation-chased', app_text, fixed = TRUE))
stopifnot(grepl('class = "search-output"', app_text, fixed = TRUE))
cat("Connect Cloud UI hotfix tests passed.\n")

app_text <- paste(readLines("app.R", warn = FALSE), collapse = "\n")
stopifnot(grepl("fillable = FALSE", app_text, fixed = TRUE))
stopifnot(grepl('Search Lens again', app_text, fixed = TRUE))
stopifnot(grepl('run_naive_lens_iteration', app_text, fixed = TRUE))
stopifnot(grepl('replace_existing = TRUE', app_text, fixed = TRUE))
stopifnot(grepl('Variants and synonyms', app_text, fixed = TRUE))
stopifnot(grepl('Add selected suggestions', app_text, fixed = TRUE))
stopifnot(grepl('external_suggestions_rows_selected', app_text, fixed = TRUE))

cat("Natural page-flow regression test passed.\n")
